query HomeDataQuery($statusVersion:Int, $season:MediaSeason, $seasonYear:Int, $nextSeason:MediaSeason, $nextYear:Int) {
  trendingAnime: Page(page: 1, perPage: 10) {
    media(type: ANIME, sort: [TRENDING_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  trendingManga: Page(page: 1, perPage: 10) {
    media(type: MANGA, sort: [TRENDING_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  popularAnime: Page(page: 1, perPage: 10) {
    media(type: ANIME, sort: [POPULARITY_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  popularManga: Page(page: 1, perPage: 10) {
    media(type: MANGA, sort: [POPULARITY_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  topAnime: Page(page: 1, perPage: 10) {
    media(type: ANIME, sort: [SCORE_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  topManga: Page(page: 1, perPage: 10) {
    media(type: MANGA, sort: [SCORE_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  currentSeasonAnime: Page(page: 1, perPage: 10) {
    media(type: ANIME, season: $season, seasonYear: $seasonYear, sort: [POPULARITY_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  nextSeasonAnime: Page(page: 1, perPage: 10) {
    media(type: ANIME, season: $nextSeason, seasonYear: $nextYear, sort: [POPULARITY_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  newAnime: Page(page: 1, perPage:10) {
    media(type: ANIME, sort: [ID_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
  newManga: Page(page: 1, perPage: 10) {
    media(type: MANGA, sort: [ID_DESC], isAdult: false) {
      ...HomeMedia
    }
  }
}

fragment HomeMedia on Media {
  id
  idMal
  title {
    romaji
    english
    native
    userPreferred
  }
  countryOfOrigin
  type
  status(version: $statusVersion)
  format
  description
  coverImage {
    extraLarge
    large
    medium
  }
  bannerImage
  genres
  averageScore
  favourites
  staff(sort:[RELEVANCE]) {
    edges {
      node {
        id
        name {
          full
        }
      }
      role
    }
  }
  studios(isMain:true) {
    edges {
      node {
        id
        name
      }
      isMain
    }
  }
  startDate {
    year
    month
    day
  }
}
